vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    # mappings:
    #   images_products: 
    #   uri_prefix: '%app.path.images_products%'
    #   upload_destination: "%kernel.project_dir%/public%app.path.images_products%"
    #   namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

